web: gunicorn semantic_service:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
worker: rq worker pdf_ingest --url rediss://:p80b713f4038e60bd498d7a5ea1877ac5e10dc603001d5e1c600d57fb72a9b6df@ec2-34-193-215-148.compute-1.amazonaws.com:16970 --with-scheduler
